//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StuAuthMobile.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StuAuthMobile.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The application is already running..
        /// </summary>
        internal static string App1 {
            get {
                return ResourceManager.GetString("App1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error: The data file is not readable on this machine. It may be corrupted or the key is incorrect. The application will now close..
        /// </summary>
        internal static string Encryption1 {
            get {
                return ResourceManager.GetString("Encryption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Decryption error.
        /// </summary>
        internal static string Encryption2 {
            get {
                return ResourceManager.GetString("Encryption2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The folder name cannot be empty..
        /// </summary>
        internal static string ErrorIntAdd {
            get {
                return ResourceManager.GetString("ErrorIntAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No account selected..
        /// </summary>
        internal static string ErrorIntDelete {
            get {
                return ResourceManager.GetString("ErrorIntDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à There is an error in your export file, please check and try again..
        /// </summary>
        internal static string ErrorIntImport {
            get {
                return ResourceManager.GetString("ErrorIntImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No account selected..
        /// </summary>
        internal static string ErrorIntRename {
            get {
                return ResourceManager.GetString("ErrorIntRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Import.
        /// </summary>
        internal static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter the folder name.
        /// </summary>
        internal static string IntAdd {
            get {
                return ResourceManager.GetString("IntAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add Folder.
        /// </summary>
        internal static string IntAdd2 {
            get {
                return ResourceManager.GetString("IntAdd2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Current version number: {0}.
        /// </summary>
        internal static string IntAppVersion {
            get {
                return ResourceManager.GetString("IntAppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Account {0} has been successfully deleted..
        /// </summary>
        internal static string IntDeleteAccount {
            get {
                return ResourceManager.GetString("IntDeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The folder {0} contains accounts. Do you want to delete it and all its accounts?.
        /// </summary>
        internal static string IntDeleteFolder1 {
            get {
                return ResourceManager.GetString("IntDeleteFolder1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Deletion confirmation.
        /// </summary>
        internal static string IntDeleteFolder2 {
            get {
                return ResourceManager.GetString("IntDeleteFolder2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The folder {0} and all its accounts have been deleted..
        /// </summary>
        internal static string IntDeleteFolder3 {
            get {
                return ResourceManager.GetString("IntDeleteFolder3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The folder {0} has been successfully deleted..
        /// </summary>
        internal static string IntDeleteFolder4 {
            get {
                return ResourceManager.GetString("IntDeleteFolder4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter a key.
        /// </summary>
        internal static string IntNewAccount {
            get {
                return ResourceManager.GetString("IntNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No QR code found.
        /// </summary>
        internal static string IntNewAccount1 {
            get {
                return ResourceManager.GetString("IntNewAccount1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The key you entered is not correct..
        /// </summary>
        internal static string IntNewAccount2 {
            get {
                return ResourceManager.GetString("IntNewAccount2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter an account name.
        /// </summary>
        internal static string IntNewAccountP2 {
            get {
                return ResourceManager.GetString("IntNewAccountP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to import the data?.
        /// </summary>
        internal static string IntNP1 {
            get {
                return ResourceManager.GetString("IntNP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The IP address is invalid or unreachable..
        /// </summary>
        internal static string IntNP2 {
            get {
                return ResourceManager.GetString("IntNP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter a correct network example: 192.168.1.
        /// </summary>
        internal static string IntNP3 {
            get {
                return ResourceManager.GetString("IntNP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The server is not started..
        /// </summary>
        internal static string IntNP4 {
            get {
                return ResourceManager.GetString("IntNP4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Import.
        /// </summary>
        internal static string IntNP5 {
            get {
                return ResourceManager.GetString("IntNP5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter the new name.
        /// </summary>
        internal static string IntRename {
            get {
                return ResourceManager.GetString("IntRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à null.
        /// </summary>
        internal static string IPApplication {
            get {
                return ResourceManager.GetString("IPApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à null.
        /// </summary>
        internal static string KeyPass {
            get {
                return ResourceManager.GetString("KeyPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à en.
        /// </summary>
        internal static string LangCode {
            get {
                return ResourceManager.GetString("LangCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter the network to scan.
        /// </summary>
        internal static string NP1 {
            get {
                return ResourceManager.GetString("NP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select an IP address.
        /// </summary>
        internal static string NP2 {
            get {
                return ResourceManager.GetString("NP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à QRCode.
        /// </summary>
        internal static string QRCode {
            get {
                return ResourceManager.GetString("QRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Register.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rename.
        /// </summary>
        internal static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Secret Key [A-Za-z0-9]:.
        /// </summary>
        internal static string SecretKey {
            get {
                return ResourceManager.GetString("SecretKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter the secret key.
        /// </summary>
        internal static string SecretKey2 {
            get {
                return ResourceManager.GetString("SecretKey2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Server.
        /// </summary>
        internal static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Desynchronization.
        /// </summary>
        internal static string Sync1 {
            get {
                return ResourceManager.GetString("Sync1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The time on your device is incorrect!.
        /// </summary>
        internal static string Sync2 {
            get {
                return ResourceManager.GetString("Sync2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The time is well synchronized.
        /// </summary>
        internal static string Sync3 {
            get {
                return ResourceManager.GetString("Sync3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Synchronization.
        /// </summary>
        internal static string Synchronization {
            get {
                return ResourceManager.GetString("Synchronization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
